### ISSUE TITLE
Controls not displaying with new @theoplayer/react-native-ui package

### ISSUE THREAD

**Issue by davidwinograd1** [THEOplayer/react-native-theoplayer-ui#8]
Adding visibility to this issue from the react-native-theoplayer package:

https://github.com/THEOplayer/react-native-theoplayer/issues/160

Would love to know any potential fix!

**Comment by ceyhun-o** [comment]
Hi @davidwinograd1,

Closing this as https://github.com/THEOplayer/react-native-theoplayer/issues/160 is resolved.

Kind regards,
Ceyhun
